### ISSUE TITLE
ImportError: No module named bluetooth._bluetooth

### ISSUE THREAD

**Issue by 103013631** [switchdoclabs/iBeacon-Scanner-#10]
Here is the error I get when I run sudo python testblescan.py

ImportError: No module named "bluetooth._bluetooth"

**Comment by sagarika4** [comment]
yeah i got the same error/

**Comment by NikNitro** [comment]
I have the same error in Windows 8.1, Windows 10 and Linux Mint.
Not in Raspbian (RP3), Openelec(RP1B) or Ubuntu (in a laptop), though.

**Comment by zumbrunnen** [comment]
Installing the package `python-bluez` should help.

**Comment by prodigyxiao** [comment]
Has someone solved this problem?

I have already had 'pybluez' package in my Raspberry Pi whereas this test code still not work.

**Comment by pengfei123xiao** [comment]
To be specific, the command should be:
'sudo apt-get install python-bluez'
for the Raspberry Pi.

**Comment by C-starm** [comment]
I have installed PyBluez 0.22 on Raspberrypi, already install python-bluez and  libbluetooth-dev. But it still don't work.

Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bluetooth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bluetooth/__init__.py", line 43, in <module>
    from .bluez import *
  File "bluetooth/bluez.py", line 6, in <module>
    import _bluetooth as _bt
ImportError: No module named _bluetooth

**Comment by licensed** [comment]
Dear, you can install pybluez package from pypi.
pip install pybluez

**Comment by simeoncapy** [comment]
I have a similar issue. But the strange thing, I can make the code works in the folder downloaded from GitHub, but when I moved the 2 files to another folder I got the error `ImportError: No module named _bluetooth`
