### ISSUE TITLE
error messages trying to run testblescan.py

### ISSUE THREAD

**Issue by wstein25** [switchdoclabs/iBeacon-Scanner-#11]
here is the response:

pi@raspberrypi:~/Switchdoc_labs $ ls
ble.py       bluetooth    **init**.py  osx.py          _widcomm.pyd
blescan.py   bluez.py     msbt.py      testblescan.py
blescan.pyc  btcommon.py  _msbt.pyd    widcomm.py
pi@raspberrypi:~/Switchdoc_labs $ sudo python testblescan.py
Traceback (most recent call last):
  File "testblescan.py", line 4, in <module>
    import blescan
  File "/home/pi/Switchdoc_labs/blescan.py", line 21, in <module>
    import bluetooth._bluetooth as bluez
  File "/home/pi/Switchdoc_labs/bluetooth/__init__.py", line 43, in <module>
    from .bluez import *
  File "/home/pi/Switchdoc_labs/bluetooth/bluez.py", line 6, in <module>
    import _bluetooth as _bt
ImportError: No module named _bluetooth
pi@raspberrypi:~/Switchdoc_labs $ 

Any ideas on what I am doing wrong?  

Thanks

**Comment by kevinpanaro** [comment]
sudo apt-get install python-bluez should fix it.
