### ISSUE TITLE
doesn't work on RPi3

### ISSUE THREAD

**Issue by janeksz** [switchdoclabs/iBeacon-Scanner-#15]
root@raspberrypi:/opt/beacon/iBeacon/iBeacon-Scanner-# python testblescanner.py
python: can't open file 'testblescanner.py': [Errno 2] No such file or directory

root@raspberrypi:/opt/beacon/iBeacon/iBeacon-Scanner-# python testblescan.py
Traceback (most recent call last):
  File "testblescan.py", line 4, in <module>
    import blescan
  File "/opt/beacon/iBeacon/iBeacon-Scanner-/blescan.py", line 21, in <module>
    import bluetooth._bluetooth as bluez
ImportError: No module named bluetooth._bluetooth
root@raspberrypi:/opt/beacon/iBeacon/iBeacon-Scanner-#

**Comment by janeksz** [comment]
@switchdoclabs can you kindly update the readme.md file - it's incorrect and confusing

**Comment by bluebolt43** [comment]
You need python bluetooth library, try "sudo apt-get install python-bluez"
